//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AutomobileInsurance
    {
        public Nullable<int> CustomerId { get; set; }
        public string VehicleType { get; set; }

        [Required(ErrorMessage = "VehicleModel field is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "At least 3 characters")]
        public string VehicleModel { get; set; }

        [Required(ErrorMessage = "VehicleNumber field is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "At least 5 characters")]
        public string VehicleNumber { get; set; }

        [Required(ErrorMessage = "VehicleAge field is required")]
        [Range(1, 100, ErrorMessage = "VehicleAge must be in range of 1-500 months")]
        public int VehicleAge { get; set; }

        [Required(ErrorMessage = "PlanDuration field is required")]
        [Range(1, 100, ErrorMessage = "PlanDuration must be in range of 1-100 years")]
        public int PlanDuration { get; set; }
        public int id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
