//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceManagementSystemDbEntities1 : DbContext
    {
        public InsuranceManagementSystemDbEntities1()
            : base("name=InsuranceManagementSystemDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutomobileInsurance> AutomobileInsurances { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<HealthInsurance> HealthInsurances { get; set; }
        public virtual DbSet<HomeInsurance> HomeInsurances { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<LifeInsurance> LifeInsurances { get; set; }
        public virtual DbSet<PensionPlan> PensionPlans { get; set; }
        public virtual DbSet<Purchased> Purchaseds { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TravelInsurance> TravelInsurances { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
