//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.Insurances = new HashSet<Insurance>();
        }
    
        public int UserId { get; set; }


        //[Required(ErrorMessage = "Username field is required")]
        //[StringLength(50, MinimumLength = 5, ErrorMessage = "At least 5 characters")]
        public string Username { get; set; }


        //[Required(ErrorMessage = "Password field is required")]
        //[StringLength(50, MinimumLength = 5, ErrorMessage = "At least 5 characters")]
        public string Password { get; set; }



        //[Required(ErrorMessage = "FirstName field is required")]
        //[RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "FirstName is not valid")]
        public string FirstName { get; set; }



        //[Required(ErrorMessage = "LastName field is required")]
        //[RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "LastName is not valid")]
        public string LastName { get; set; }
        
        public System.DateTime RegistrationDate { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance> Insurances { get; set; }
        public virtual Role Role { get; set; }
    }
}
